### ISSUE TITLE
Fix Webpack build

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder#112]
`webpacker:compile` hangs after start.

Could be caused by `erb-loader`.

Update: `./bin/webpack --progress --verbose` displays this:

```
ERROR in ./app/javascript/packs/hello_erb.js.erb
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/app/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by dreikanter** [comment]
Got this error after clean webpacker installation:

> Integrity check: Flags don't match

Fix:

- https://github.com/rails/webpacker/issues/1529
- https://github.com/usabilityhub/rails-erb-loader/issues/63

Also got this warning:

> WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
>
> You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:
>
>  npm install --save core-js@2    npm install --save core-js@3
>  yarn add core-js@2              yarn add core-js@3

Fix:

    yarn add core-js@2
