### ISSUE TITLE
Fix Webpack build hanging for an unknown reason

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder#122]
Related: #112

**Comment by dreikanter** [comment]
Potential fix: https://github.com/usabilityhub/rails-erb-loader/issues/47#issuecomment-434138107

**Comment by dreikanter** [comment]
The issue is related to Spring. `spring stop` may help.

**Comment by dreikanter** [comment]
`bin/webpack` works. `rails webpacker:compile` fails:

```
Compiling…
Compilation failed:
warning Integrity check: Flags don't match
error Integrity check failed
error Found 1 errors.


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).


yarn check v1.15.2
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.



Hash: 5224025564d29a070234
Version: webpack 4.33.0
Time: 6983ms
Built at: 06/09/2019 12:30:46 PM
 2 assets
Entrypoint application = js/application-3d27c647f76150a6c60f.js js/application-3d27c647f76150a6c60f.js.map
  [2] ./client/main/paths.js.erb 424 bytes {0} [built] [failed] [1 error]
  [6] (webpack)/buildin/global.js 878 bytes {0} [built]
 [52] (webpack)/buildin/harmony-module.js 631 bytes {0} [built]
[140] ./client/main/layout.scss 1.45 KiB {0} [built]
[141] ../node_modules/css-loader??ref--8-1!./node_modules/postcss-loader/src??ref--8-2!./node_modules/sass-loader/lib/loader.js??ref--8-3!./client/main/layout.scss 1.65 KiB {0} [built]
[144] ./client/packs/application.js + 64 modules 152 KiB {0} [built]
      | ./client/packs/application.js 270 bytes [built]
      | ./client/main/index.js 655 bytes [built]
      | ./client/main/store.js 715 bytes [built]
      | ./client/main/routes.js 157 bytes [built]
      | ./client/main/createReducer.js 355 bytes [built]
      | ./client/main/initState.js 155 bytes [built]
      | ./client/index/index.js 39 bytes [built]
      | ./client/main/routingPaths.js 1.02 KiB [built]
      | ./client/main/reducers/feedReducer.js 401 bytes [built]
      | ./client/main/reducers/indexReducer.js 408 bytes [built]
      | ./client/main/reducers/pendingReducer.js 759 bytes [built]
      | ./client/index/initState.js 25 bytes [built]
      | ./client/main/actions/loadFeed.js 433 bytes [built]
      | ./client/main/actions/loadFeeds.js 410 bytes [built]
      | ./client/main/utils/promiseHelpers.js 352 bytes [built]
      |     + 50 hidden modules
    + 140 hidden modules

ERROR in ./client/main/paths.js.erb
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/Users/dreikanter/Sources/feeder/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
 @ ./client/main/routingPaths.js 1:690-720 4:28-33
 @ ./client/main/routes.js
 @ ./client/main/index.js
 @ ./client/packs/application.js
```

**Comment by dreikanter** [comment]
Workaround: direct `webpack` and `webpack-dev-server` execution works.
