### ISSUE TITLE
Fix bazar feed comments

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder#276]
```ruby
puts JSON.pretty_generate Error.where("line_number" => 22).last.attributes.as_json
```

```json
{
  "id": 199,
  "status": "pending",
  "exception": "Freefeed::Error::BadRequest",
  "file_name": "",
  "line_number": 22,
  "label": "",
  "message": "Freefeed::Error::BadRequest",
  "backtrace": [
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/freefeed-0.5.4/lib/freefeed/request.rb:22:in `call'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/freefeed-0.5.4/lib/freefeed/utils.rb:9:in `authenticated_request'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/freefeed-0.5.4/lib/freefeed/v1/comments.rb:9:in `create_comment'",
    "/app/app/services/push.rb:40:in `block in create_comments'",
    "/app/app/services/push.rb:39:in `each'",
    "/app/app/services/push.rb:39:in `create_comments'",
    "/app/app/services/push.rb:17:in `publish_post_content'",
    "/app/app/services/push.rb:8:in `call'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/callee-0.3.5/lib/callee.rb:12:in `call'",
    "/app/app/jobs/push_job.rb:5:in `perform'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/execution.rb:48:in `block in perform_now'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:117:in `block in run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/marginalia-1.10.0/lib/marginalia/railtie.rb:37:in `block (2 levels) in insert_into_active_job'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/i18n-1.8.7/lib/i18n.rb:313:in `with_locale'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/instrumentation.rb:21:in `block in instrument'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/notifications.rb:203:in `block in instrument'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/notifications.rb:203:in `instrument'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/instrumentation.rb:28:in `instrument'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/logging.rb:22:in `block in tag_logger'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/logging.rb:22:in `tag_logger'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:137:in `run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/execution.rb:47:in `perform_now'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/execution.rb:25:in `block in execute'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:117:in `block in run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/execution_wrapper.rb:88:in `wrap'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/reloader.rb:72:in `block in wrap'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/execution_wrapper.rb:88:in `wrap'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/reloader.rb:71:in `wrap'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `instance_exec'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:126:in `block in run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/callbacks.rb:137:in `run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/execution.rb:23:in `execute'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activejob-6.1.0/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/backend/base.rb:81:in `block in invoke_job'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/honeybadger-4.7.2/lib/honeybadger/plugins/delayed_job/plugin.rb:37:in `block (2 levels) in <class:Plugin>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:79:in `block in add'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/backend/base.rb:78:in `invoke_job'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:230:in `block (2 levels) in run'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/timeout.rb:103:in `timeout'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:230:in `block in run'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:229:in `run'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:213:in `block in work_off'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:212:in `times'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:212:in `work_off'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:175:in `block (4 levels) in start'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:174:in `block (3 levels) in start'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:173:in `block (2 levels) in start'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:172:in `loop'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:172:in `block in start'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:79:in `block in add'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:171:in `start'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.9/lib/delayed/tasks.rb:14:in `block (2 levels) in <top (required)>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/rake_module.rb:59:in `with_application'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/commands/rake/rake_command.rb:18:in `perform'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/command.rb:52:in `invoke'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/commands.rb:18:in `<top (required)>'",
    "/app/bin/rails:9:in `require'",
    "/app/bin/rails:9:in `<top (required)>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'",
    "/home/vagrant/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'",
    "/app/bin/spring:13:in `<top (required)>'",
    "bin/rails:3:in `load'",
    "bin/rails:3:in `<main>'"
  ],
  "context": {
    "class_name": "PushJob"
  },
  "occured_at": "2021-01-05T04:18:45.719Z",
  "created_at": "2021-01-05T04:18:45.721Z",
  "updated_at": "2021-01-05T04:18:45.721Z",
  "target_type": "Post",
  "target_id": 973
}
```

```ruby
Post.find(973)
```

```ruby
{
                   :id => 973,
              :feed_id => 230,
                 :link => "https://meduza.io/episodes/2020/11/25/glava-v-kotoroy-deti-rasskazyvayut-serieznye-istorii-oni-bolshe-ne-autsaydery-ne-milye-kroshki-i-nositeli-horrora-a-normalnye-obychnye-lyudi",
         :published_at => Wed, 25 Nov 2020 13:34:51.000000000 UTC +00:00,
                 :text => "Глава, в которой дети рассказывают серьезные истории. Они больше не аутсайдеры, не «милые крошки» и «носители хоррора», а нормальные, обычные люди - https://meduza.io/episodes/2020/11/25/glava-v-kotoroy-deti-rasskazyvayut-serieznye-istorii-oni-bolshe-ne-autsaydery-ne-milye-kroshki-i-nositeli-horrora-a-normalnye-obychnye-lyudi\n\nЗапись: http://meduza.io/audio/1606311697/episodes/2020/11/25/glava-v-kotoroy-deti-rasskazyvayut-serieznye-istorii-oni-bolshe-ne-autsaydery-ne-milye-kroshki-i-nositeli-horrora-a-normalnye-obychnye-lyudi.mp3 (51:44)",
          :attachments => [],
             :comments => [
        [0] "<p>В последние тридцать лет писатели все чаще используют образ ребенка в «недетской» литературе. И хотя этот трюк проворачивали еще Толстой и Диккенс, настоящий прорыв случился после книг о Гарри Поттере: читать про подростков стало так же интересно, как и про взрослых. В новом эпизоде подкаста «Книжный базар» об этом феномене рассказывают литературный обозреватель «Медузы» Галина Юзефович и главный редактор книжного сервиса Storytel Анастасия Завозова. </p>\n<p>«Дети не такие!»: за что критики ругали «Осиную фабрику» Иэна Бэнкса? С каких пор с ребенка сошло клеймо «милой крошки»? Как Оливер Твист и Дэвид Копперфильд заставили читателей смотреть на мрачный мир незамутненным, детским взглядом? И как этот прием используется в «Комнате» и «Мальчике в полосатой пижаме»? Правда, что авторы манипулируют нами с помощью детей? И вообще — не злоупотребляют ли писатели образом детей-аутсайдеров? «Нет зверя страшнее девочки в пубертате!»: как детскую тему использует Стивен Кинг? И почему дети в хоррорах наводят на нас такой ужас?</p>\n<p><strong>Рекомендации:</strong></p>\n<ul><li>«Живые и взрослые», Сергей Кузнецов</li>\n<li>«Посредник», Лесли Поулз Хартли </li>\n<li>\n<a href=\"https://meduza.io/feature/2016/04/30/15-knig-chtoby-zabyt-pro-mayskie-prazdniki\" target=\"_blank\">«Самая прекрасная земля на свете»</a>, Грейс Макклин</li>\n<li>«Последний самурай», Хелен Девитт</li>\n<li>\n<a href=\"https://meduza.io/feature/2016/04/30/15-knig-chtoby-zabyt-pro-mayskie-prazdniki\" target=\"_blank\">«Кошкин стол»</a>, Майкл Ондатже</li>\n<li>«Библиотека на Обугленной горе», Скотт Хокинс</li></ul>\n\n<p>❗️В конце сезона Галя и Настя, как обычно, ответят на ваши вопросы. Присылайте письма на почту podcasts@meduza.io с пометкой «Книжный базар».</p>"
    ],
     :freefeed_post_id => "2205dad4-6b30-4afd-a35c-c7923cbec231",
           :created_at => Tue, 05 Jan 2021 04:07:56.530216000 UTC +00:00,
           :updated_at => Tue, 05 Jan 2021 04:18:45.712667000 UTC +00:00,
               :status => "error",
                  :uid => "https://meduza.io/episodes/2020/11/25/glava-v-kotoroy-deti-rasskazyvayut-serieznye-istorii-oni-bolshe-ne-autsaydery-ne-milye-kroshki-i-nositeli-horrora-a-normalnye-obychnye-lyudi",
    :validation_errors => []
}
```

**Comment by dreikanter** [comment]
Feed is inactive.
