### ISSUE TITLE
URI must be ascii only

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder#36]
```
URI must be ascii only "https://www.commitstrip.com/wp-content/uploads/2017/06/Strip-lappel-du-c\u00F4t\u00E9-obscur-english.jpg"
   (0.3ms)  BEGIN /*application:Feeder,line:/app/models/error.rb:48:in `dump'*/
  SQL (1.5ms)  INSERT INTO "errors" ("error_class_name", "file_name", "line_number", "label", "message", "backtrace", "filtered_backtrace", "context", "occured_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id" /*application:Feeder,line:/app/models/error.rb:48:in `dump'*/  [["error_class_name", "URI::InvalidURIError"], ["file_name", "/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/uri/rfc3986_parser.rb"], ["line_number", 21], ["label", "split"], ["message", "URI must be ascii only \"https://www.commitstrip.com/wp-content/uploads/2017/06/Strip-lappel-du-c\\u00F4t\\u00E9-obscur-english.jpg\""], ["backtrace", "{\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/uri/rfc3986_parser.rb:21:in `split'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/uri/common.rb:231:in `parse'\",\"/app/lib/freefeed/client.rb:87:in `path_from_url'\",\"/app/lib/freefeed/client.rb:11:in `create_attachment_from_url'\",\"/app/app/jobs/push_job.rb:21:in `block in perform'\",\"/app/app/jobs/push_job.rb:19:in `map'\",\"/app/app/jobs/push_job.rb:19:in `perform'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:37:in `block in perform_now'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/marginalia-1.4.0/lib/marginalia/railtie.rb:37:in `block (2 levels) in insert_into_active_job'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/i18n-0.8.4/lib/i18n.rb:257:in `with_locale'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `block in tag_logger'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `tag_logger'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:33:in `perform_now'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:22:in `block in execute'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:68:in `block in wrap'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:67:in `wrap'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:20:in `execute'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activejob-5.1.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:36:in `perform'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:81:in `block in invoke_job'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:78:in `invoke_job'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block (2 levels) in run'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block in run'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:229:in `run'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:213:in `block in work_off'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `times'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `work_off'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:175:in `block (4 levels) in start'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:174:in `block (3 levels) in start'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:173:in `block (2 levels) in start'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `loop'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `block in start'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block in add'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:171:in `start'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/delayed_job-4.1.3/lib/delayed/tasks.rb:14:in `block (2 levels) in <top (required)>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/command.rb:46:in `invoke'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'\",\"/app/bin/rails:9:in `require'\",\"/app/bin/rails:9:in `<top (required)>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'\",\"/app/bin/spring:13:in `<top (required)>'\",\"bin/rails:3:in `load'\",\"bin/rails:3:in `<main>'\"}"], ["filtered_backtrace", "{\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/uri/rfc3986_parser.rb:21:in `split'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/uri/common.rb:231:in `parse'\",\"/lib/freefeed/client.rb:87:in `path_from_url'\",\"/lib/freefeed/client.rb:11:in `create_attachment_from_url'\",\"/jobs/push_job.rb:21:in `block in perform'\",\"/jobs/push_job.rb:19:in `map'\",\"/jobs/push_job.rb:19:in `perform'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'\",\"/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'\",\"/bin/spring:13:in `<top (required)>'\"}"], ["context", "{\"context\":{\"class_name\":\"PushJob\"}}"], ["occured_at", "2017-06-16 08:48:41.397621"], ["created_at", "2017-06-16 08:48:41.400123"], ["updated_at", "2017-06-16 08:48:41.400123"]]
   (1.0ms)  COMMIT /*application:Feeder,line:/app/models/error.rb:48:in `dump'*/
   (0.3ms)  BEGIN /*application:Feeder,line:/app/jobs/push_job.rb:8:in `block in <class:PushJob>'*/
  SQL (0.6ms)  UPDATE "posts" SET "status" = $1, "updated_at" = $2 WHERE "posts"."id" = $3 /*application:Feeder,line:/app/jobs/push_job.rb:8:in `block in <class:PushJob>'*/  [["status", 3], ["updated_at", "2017-06-16 08:48:41.410783"], ["id", 5516]]
   (0.9ms)  COMMIT /*application:Feeder,line:/app/jobs/push_job.rb:8:in `block in <class:PushJob>'*/
   (0.1ms)  BEGIN /*application:Feeder,line:/bin/rails:9:in `require'*/
  SQL (0.5ms)  DELETE FROM "delayed_jobs" WHERE "delayed_jobs"."id" = $1 /*application:Feeder,line:/bin/rails:9:in `require'*/  [["id", 62017]]
```

**Comment by dreikanter** [comment]
https://github.com/httprb/http/issues/196
