### ISSUE TITLE
Fix normalization for CommitStrip

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder#40]
```
[ActiveJob] [PushJob] [72215fdc-2284-46e5-afff-984a457e5dce] Performing PushJob (Job ID: 72215fdc-2284-46e5-afff-984a457e5dce) from DelayedJob(default) with arguments: #<GlobalID:0x00000004e8edc0 @uri=#<URI::GID gid://feeder/Post/88>>
[ActiveJob] [PushJob] [72215fdc-2284-46e5-afff-984a457e5dce] create new attachment for https://www.commitstrip.com/wp-content/uploads/2017/09/Strip-La-réunion-qui-fait-perdre-du-temps-english650-final.jpg
[ActiveJob] [PushJob] [72215fdc-2284-46e5-afff-984a457e5dce] Error performing PushJob (Job ID: 72215fdc-2284-46e5-afff-984a457e5dce) from DelayedJob(default) in 1.88ms: URI::InvalidURIError (URI must be ascii only "https://www.commitstrip.com/wp-content/uploads/2017/09/Strip-La-r\u00E9union-qui-fait-perdre-du-temps-english650-final.jpg"):
/usr/lib/ruby/2.4.0/uri/rfc3986_parser.rb:21:in `split'
/usr/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
/usr/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
/home/vagrant/.gem/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:597:in `parse_url_with_auth!'
/home/vagrant/.gem/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:72:in `initialize'
/home/vagrant/.gem/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `new'
/home/vagrant/.gem/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/home/vagrant/.gem/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient.rb:67:in `get'
/app/lib/freefeed/client.rb:14:in `block in create_attachment_from_url'
/usr/lib/ruby/2.4.0/tempfile.rb:295:in `open'
/app/lib/freefeed/client.rb:11:in `create_attachment_from_url'
/app/app/jobs/push_job.rb:21:in `block in perform'
/app/app/jobs/push_job.rb:19:in `map'
/app/app/jobs/push_job.rb:19:in `perform'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/execution.rb:37:in `block in perform_now'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/marginalia-1.4.0/lib/marginalia/railtie.rb:37:in `block (2 levels) in insert_into_active_job'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/i18n-0.8.6/lib/i18n.rb:257:in `with_locale'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:166:in `block in instrument'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:166:in `instrument'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/logging.rb:44:in `block in tag_logger'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/logging.rb:44:in `tag_logger'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/execution.rb:33:in `perform_now'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/execution.rb:22:in `block in execute'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/reloader.rb:68:in `block in wrap'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/reloader.rb:67:in `wrap'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/execution.rb:20:in `execute'
/home/vagrant/.gem/ruby/2.4.0/gems/activejob-5.1.3/lib/active_job/queue_adapters/delayed_job_adapter.rb:36:in `perform'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:78:in `invoke_job'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block in run'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:229:in `run'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:213:in `block in work_off'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `times'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `work_off'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `loop'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `block in start'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block in add'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:171:in `start'
/home/vagrant/.gem/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/tasks.rb:14:in `block (2 levels) in <top (required)>'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/vagrant/.gem/ruby/2.4.0/gems/railties-5.1.3/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/vagrant/.gem/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/vagrant/.gem/ruby/2.4.0/gems/railties-5.1.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/vagrant/.gem/ruby/2.4.0/gems/railties-5.1.3/lib/rails/command.rb:46:in `invoke'
/home/vagrant/.gem/ruby/2.4.0/gems/railties-5.1.3/lib/rails/commands.rb:16:in `<top (required)>'
/app/bin/rails:9:in `require'
/app/bin/rails:9:in `<top (required)>'
/home/vagrant/.gem/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/vagrant/.gem/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/vagrant/.gem/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/vagrant/.gem/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/vagrant/.gem/ruby/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/vagrant/.gem/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/vagrant/.gem/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/usr/local/lib/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/app/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
URI must be ascii only "https://www.commitstrip.com/wp-content/uploads/2017/09/Strip-La-r\u00E9union-qui-fait-perdre-du-temps-english650-final.jpg"
```

**Comment by dreikanter** [comment]
French URIs, ugh.
