### ISSUE TITLE
Fix GitHub feed

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder#45]
```
#<Error:0x0055be3d80e750
 id: 127032,
 status: "pending",
 error_class_name: "NoMethodError",
 file_name:
  "/var/www/feeder/releases/feeder-20170919212308/app/entity_normalizers/atom_normalizer.rb",
 line_number: 8,
 label: "published_at",
 message: "undefined method `content' for nil:NilClass",
 backtrace:
  ["/var/www/feeder/releases/feeder-20170919212308/app/entity_normalizers/atom_normalizer.rb:8:in `published_at'",
   "/var/www/feeder/releases/feeder-20170919212308/app/entity_normalizers/base.rb:50:in `block in attributes'",
   "/var/www/feeder/releases/feeder-20170919212308/app/entity_normalizers/base.rb:50:in `map'",
   "/var/www/feeder/releases/feeder-20170919212308/app/entity_normalizers/base.rb:50:in `attributes'",
   "/var/www/feeder/releases/feeder-20170919212308/app/entity_normalizers/base.rb:4:in `process'",
   "/var/www/feeder/releases/feeder-20170919212308/app/service/feed_normalizer.rb:23:in `entity_attributes'",
   "/var/www/feeder/releases/feeder-20170919212308/app/service/feed_normalizer.rb:8:in `process'",
   "/var/www/feeder/releases/feeder-20170919212308/app/jobs/pull_job.rb:23:in `block in perform'",
   "/var/www/feeder/releases/feeder-20170919212308/app/jobs/pull_job.rb:18:in `each'",
   "/var/www/feeder/releases/feeder-20170919212308/app/jobs/pull_job.rb:18:in `each'",
   "/var/www/feeder/releases/feeder-20170919212308/app/jobs/pull_job.rb:18:in `perform'",
```

**Comment by dreikanter** [comment]
```
"/var/www/feeder/releases/feeder-20170919212308/app/entity_normalizers/atom_normalizer.rb:8"=>
  {"id"=>127032,
   "status"=>"pending",
   "error_class_name"=>"NoMethodError",
   "file_name"=>
    "/var/www/feeder/releases/feeder-20170919212308/app/entity_normalizers/atom_normalizer.rb",
   "line_number"=>8,
   "label"=>"published_at",
   "message"=>"undefined method `content' for nil:NilClass"},
```
