### ISSUE TITLE
Import Safely Endangered feed

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder#92]
- Take a look at the codebase and this [wiki page](https://github.com/dreikanter/feeder/wiki/Adding-feeds) to see how to import a new feed.
- The update should include configuration file update, a processor and a normalizer classes, specific to the new feed. Probably a new loader as well, unless one of the existing loaders will fit.
- There is no need to test the update on staging (candy.freefeed.net) or do any production related operations, I'll take care of it.

References:

- Source: https://www.webtoons.com/en/comedy/safely-endangered/list?title_no=352&webtoon-platform-redirect=true

**Comment by dreikanter** [comment]
Date parse error:

```
RSS::NotAvailableValueError: value <Wednesday, 11 Sep 2019 01:00:39 GMT> of tag <lastBuildDate> is not available.
from /Users/dreikanter/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rss/0.9.rb:141:in `rescue in lastBuildDate='
Caused by ArgumentError: not RFC 2822 compliant date: "Wednesday, 11 Sep 2019 01:00:39 GMT"
from /Users/dreikanter/.rbenv/versions/2.6.3/lib/ruby/2.6.0/time.rb:524:in `rfc2822'
```

**Comment by dreikanter** [comment]
@safelyendangered - Safely Endangered web comic by Chris McCoy - https://twitter.com/EndangeredComic
